# Generated by Django 4.0.4 on 2025-09-24 09:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_property_image_remove_property_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_title',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
